name: Build and Push to GCR

on:
  push:
    branches: [ main ]

# Environment variables available to all jobs and steps in this workflow
#  GKE_EMAIL: ${{ secrets.GKE_EMAIL }} 
#  GKE_KEY: ${{ secrets.GKE_KEY }} 
env:
  GITHUB_SHA: ${{ github.sha }} 
  GITHUB_REF: ${{ github.ref }} 
  IMAGE: nodetry
  REGISTRY_HOSTNAME: gcr.io
  PROJECT_ID: ${{ secrets.PROJ_ID}}


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
    - name: trying this action
      uses: raccoondev/push-docker-gcr
        with:
          gcr_host: eu.gcr.io
          image_name: nodetry
          image_tag: latest
          env:
            GCLOUD_SERVICE_KEY: ${{ secrets.GCR_KEY }}
            GOOGLE_PROJECT_ID: ${{ secrets.PROJ_ID }}
    # # Setup gcloud CLI
    # # - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
    # #   with:
    # #     version: '270.0.0'
    # #     service_account_key: ${{ secrets.GCR_KEY }} 
    # - name: Setup Google Cloud SDK
    #   uses: mathieu-bour/setup-gcloud@1.3.0
    #   with:
    #     service-account-key: ${{ secrets.GCR_KEY }} # base64-encoded service account JSON key
    #     confgure-docker: true
    # # Configure docker to use the gcloud command-line tool as a credential helper
    # - run: |
    #     # Set up docker to authenticate
    #     # via gcloud command-line tool.
    #     gcloud auth configure-docker

    # # Build the Docker image
    # - name: Build
    #   run: |
    #     docker build -t "$REGISTRY_HOSTNAME"/"$PROJECT_ID"/"$IMAGE":"$GITHUB_SHA" .

    # # Push the Docker image to Google Container Registry
    # - name: Publish
    #   run: |
    #     docker push "$REGISTRY_HOSTNAME"/"$PROJECT_ID"/"$IMAGE":"$GITHUB_SHA"
    #     docker tag "$REGISTRY_HOSTNAME"/"$PROJECT_ID"/"$IMAGE":"$GITHUB_SHA" "$REGISTRY_HOSTNAME"/"$IMAGE":latest
    #     docker push "$REGISTRY_HOSTNAME"/"$PROJECT_ID"/"$IMAGE":latest