name: Build and Push to GCR

on:
  push:
    branches: [ main ]

# Environment variables available to all jobs and steps in this workflow
#  GKE_EMAIL: ${{ secrets.GKE_EMAIL }} 
#  GKE_KEY: ${{ secrets.GKE_KEY }} 
env:
  GITHUB_SHA: ${{ github.sha }} 
  GITHUB_REF: ${{ github.ref }} 
  IMAGE: nodetry
  REGISTRY_HOSTNAME: gcr.io
  PROJECT_ID: ${{ secrets.PROJ_ID}}
  SERVICE: nodetry
  REGION: us-central1


jobs:
  deploy:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: {{ secrets.GCR_KEY}}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and Push Container
      run: |-
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }} .
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}
    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy ${{ env.SERVICE }} \
          --region ${{ env.REGION }} \
          --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }} \
          --platform "managed" \
          --quiet


    # - name: Set up gcloud Cloud SDK environment
    #   uses: google-github-actions/setup-gcloud@v0.6.0

    # Setup gcloud CLI
    # - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
    #   with:
    #     version: '270.0.0'
    #     service_account_key: ${{ secrets.GCR_KEY }} 
    # - name: Setup Google Cloud SDK
    #   uses: mathieu-bour/setup-gcloud@1.3.0
    #   with:
    #     service-account-key: ${{ secrets.GCR_KEY }} # base64-encoded service account JSON key
    #     confgure-docker: true
    # - id: 'auth'
    #   uses: 'google-github-actions/auth@v0'
    #   with:
    #     credentials_json: ${{ secrets.GCR_KEY }}

    # - name: 'Set up Cloud SDK'
    #   uses: 'google-github-actions/setup-gcloud@v0'

    # # Configure docker to use the gcloud command-line tool as a credential helper
    # - run: |
    #     # Set up docker to authenticate
    #     # via gcloud command-line tool.
    #     gcloud auth configure-docker

    # # Build the Docker image
    # - name: Build
    #   run: |
    #     docker build -t "$REGISTRY_HOSTNAME"/"$PROJECT_ID"/"$IMAGE":"$GITHUB_SHA" .

    # # Push the Docker image to Google Container Registry
    # - name: Publish
    #   run: |
    #     docker push "$REGISTRY_HOSTNAME"/"$PROJECT_ID"/"$IMAGE":"$GITHUB_SHA"
    #     docker tag "$REGISTRY_HOSTNAME"/"$PROJECT_ID"/"$IMAGE":"$GITHUB_SHA" "$REGISTRY_HOSTNAME"/"$IMAGE":latest
    #     docker push "$REGISTRY_HOSTNAME"/"$PROJECT_ID"/"$IMAGE":latest